---
name: GEOS wheels
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "tmate debugging enabled"
        required: false
        default: false
  pull_request:

env:
  WHEEL_SDIR: wheelhouse

jobs:
  build_psutil:
    name: Build wheels of psutil  on ${{ matrix.os }} 
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: windows-intel
            runs-on: windows-latest
          - os: windows-arm
            runs-on: windows-11-arm
          - os: macos-intel
            # macos-15-intel is the last x86_64 runner
            runs-on: macos-15-intel
          - os: macos-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
    env:
      REPO_DIR: psutil
      BUILD_COMMIT: release-7.0.0
      WHEEL_SDIR: wheelhouse
    steps:
      - uses: actions/checkout@v6
      - name: get code of psutil
        run: |
          echo $PATH
          bash -x .github/workflows/code.sh
          pwd
          ls -lrt
          sleep 180
      - name: Build Wheel of psutil
        uses: pypa/cibuildwheel@v4.0.0
        with:
          package-dir: ./psutil
          output-dir: wheelhouse

  build_pyproj:
    name: Build wheels of pyproj  on ${{ matrix.os }} 
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: windows-intel
            runs-on: windows-latest
          - os: windows-arm
            runs-on: windows-11-arm
          - os: macos-intel
            # macos-15-intel is the last x86_64 runner
            runs-on: macos-15-intel
          - os: macos-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
    env:
      REPO_DIR: pyproj
      BUILD_COMMIT: 3.7.2
      WHEEL_SDIR: wheelhouse
    steps:
      - uses: actions/checkout@v6
      - name: get code of pyproj
        run: |
          echo $PATH
          bash -x .github/workflows/code.sh
      - name: Build Wheel of psutil
        uses: pypa/cibuildwheel@v4.0.0
