---
name: GDAL wheels
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "tmate debugging enabled"
        required: false
        default: false
  pull_request:
env:
  WHEEL_SDIR: wheelhouse
jobs:
  build_GDAL_OSX_arm64:
    name: GDAL ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        python: ["3.11", "3.12", "3.13"]
        platform: ["arm64"]
        macos-target: ["13"]
        os-name: ["osx"]
    env:
      REPO_DIR: gdal
      BUILD_COMMIT: v3.13.1
      WHEEL_SDIR: wheelhouse
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "wheel numpy==2.2.6 build pip==25.2 Cython==3.1.4 setuptools==80.9.0 tomli==2.2.1 versioneer[toml]==0.28"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v6
      - name: Get code of gdal
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          bash -x .github/workflows/build.sh
      - name: Build Wheel of GDAL
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v7
        with:
          name: "wheels_gdal_${{ matrix.python }}"
          path: wheelhouse/gdal*whl

  build_GDAL_Linux_x86_64:
    name: GDAL ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python: ["3.11", "3.12", "3.13"]
        platform: ["x86_64"]
    env:
      REPO_DIR: gdal
      BUILD_COMMIT: v3.13.1
      WHEEL_SDIR: wheelhouse
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "wheel numpy==2.2.6 build pip==25.2 Cython==3.1.4 setuptools==80.9.0 tomli==2.2.1 versioneer[toml]==0.28"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup cmake
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          echo $PATH
          echo "check python3"
          python3 -c "import sys; print(sys.version)"
      - name: Get code of gdal
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          bash -x .github/workflows/build.sh
      - name: Build Wheel of GDAL
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v7
        with:
          name: "wheels_gdal_${{ matrix.python }}"
          path: wheelhouse/gdal*whl
