---
name: Geopandas test wheels x86_64
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "tmate debugging enabled"
        required: false
        default: false
  pull_request:

env:
  WHEEL_SDIR: wheelhouse

jobs:
  build_GEOS:
    name: GDAL ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python: ["3.12"]
        platform: ["x86_64"]
        os-name: ["jammy"]
    env:
      REPO_DIR: gdal
      BUILD_COMMIT: v3.10.1
      WHEEL_SDIR: wheelhouse
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "wheel numpy==2.2.6 setuptools"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: get code of GDAL
        run: |
          bash -x .github/workflows/build.sh
      - name: Build Wheel of GDAL
        run: |
          sudo apt install python3-virtualenv
          bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v4
        with:
          name: "wheels_gdal_${{ matrix.python }}"
          path: wheelhouse
      - name: Setup debugging session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 180
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Test wheels with python ${{ matrix.python-version }}
        shell: bash
        run: |
          set -x
          echo "engine installation to test wheel"
          python3 -m venv $HOME/openquake
          source $HOME/openquake/bin/activate
          pip install -U pip wheel setuptools
          cd ${{steps.download.outputs.download-path}}
          PYCUT=`echo "${PYTHON_VERSION//.}"`
          cd $HOME
          git clone -b ${BRANCH_TEST} https://github.com/gem/oq-engine.git
          cd oq-engine
          git status
          pip install -r requirements-py"${PYCUT}"-linux64.txt
          cd $HOME
          find . -name \*cp"${PYCUT}"\* -type f -print0 | xargs -0 pip install --force-reinstall
          pip install -e oq-engine/
          cd $HOME/oq-engine
          oq engine --upgrade-db
          sleep 5
          pytest -vsx --color=yes openquake/sep/tests/test_utils.py
          pytest -vsx --color=yes openquake/sep
          pytest -vsx --color=yes openquake/hazardlib/tests/gsim/kotha_2020_test.py
          oq engine --run https://downloads.openquake.org/jobs/risk_test.zip
