---
name: geopandas, pyogrio wheels x86_64
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "tmate debugging enabled"
        required: false
        default: false
  pull_request:

env:
  WHEEL_SDIR: wheelhouse

jobs:
  build_pyogrio:
    name: pyogrio ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python: ["3.11", "3.12"]
        platform: ["x86_64"]
        os-name: ["jammy"]
    env:
      REPO_DIR: pyogrio
      BUILD_COMMIT: v0.11.1
      WHEEL_SDIR: wheelhouse
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "wheel numpy==2.2.6 setuptools==69.0.2"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: get code of pyogrio
        run: |
          bash -x .github/workflows/build.sh
      - name: Build Wheel of pyogrio
        run: |
          sudo apt install python3-virtualenv
          bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v4
        with:
          name: "wheels_gdal_${{ matrix.python }}"
          path: wheelhouse/pyogrio*whl

