---
name: Linux GDAL x86_64

on: [workflow_dispatch]

env:
  REPO_DIR: gdal
  WHEEL_SDIR: wheelhouse
  SETUPTOOLS_USE_DISTUTILS: stdlib

jobs:
  build:
    name: GDAL ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-22.04" ]
        python: [ "3.8", "3.9", "3.10" ]
        platform: [ "x86_64"]
        os-name: ["jammy"]
    env:
      BUILD_COMMIT: v3.4.3
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "numpy==1.23.3 wheel"
      TEST_DEPENDS: "numpy==1.13.3"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: get code of GDAL
        env:
          REPO_DIR: gdal
          WHEEL_SDIR: wheelhouse
          SETUPTOOLS_USE_DISTUTILS: stdlib
          BUILD_COMMIT: v3.4.3
        run: |
            bash -x .github/workflows/build.sh
      - name: Build Wheel of Fiona
        env:
          REPO_DIR: gdal/gdal/swig/python
          WHEEL_SDIR: wheelhouse
          SETUPTOOLS_USE_DISTUTILS: stdlib
          BUILD_COMMIT: v3.4.3
        run: |
            sudo apt install python3-virtualenv
            bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
