---
name: Linux Fiona x86_64

on: [pull_request, workflow_dispatch]

env:
  REPO_DIR: Fiona
  WHEEL_SDIR: wheelhouse
  SETUPTOOLS_USE_DISTUTILS: stdlib

jobs:
  build:
    name: Fiona ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-22.04" ]
        python: [ "3.8", "3.9", "3.10" ]
        platform: [ "x86_64"]
        os-name: ["jammy"]
    env:
      BUILD_COMMIT: 1.8.21
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "oldest-supported-numpy cython==0.29.26 wheel==0.34.2"
      TEST_DEPENDS: "oldest-supported-numpy attrs==21.4.0 pytest==6.2.5 click==8.0.3 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2 pytz"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: get code of Fiona
        env:
          REPO_DIR: Fiona
          WHEEL_SDIR: wheelhouse
          SETUPTOOLS_USE_DISTUTILS: stdlib
          BUILD_COMMIT: 1.8.21
        run: |
            echo $PATH
            bash -x .github/workflows/build.sh
      - name: Build Wheel of Fiona
        env:
          REPO_DIR: Fiona
          WHEEL_SDIR: wheelhouse
          SETUPTOOLS_USE_DISTUTILS: stdlib
          BUILD_COMMIT: 1.8.21
          BUILD_DEPENDS: "oldest-supported-numpy cython==0.29.26 wheel==0.34.2"
          TEST_DEPENDS: "oldest-supported-numpy attrs==21.4.0 pytest==6.2.5 click==8.0.3 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2 pytz"
        run: |
            echo $PATH
            sudo apt install python3-virtualenv
            bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
