---
name: MacOS GDAL x86_64

on: [push, pull_request, workflow_dispatch]

env:
  REPO_DIR: gdal
  WHEEL_SDIR: wheelhouse
  SETUPTOOLS_USE_DISTUTILS: stdlib

jobs:
  build:
    name: GDAL ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-12" ]
        python: [ "3.9" ]
        platform: [ "x86_64"]
        macos-target: [ "11" ]
        os-name: ["osx"]
    env:
      BUILD_COMMIT: v3.4.3
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "numpy==1.23.3 wheel"
      TEST_DEPENDS: "numpy==1.23.3"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup cmake
        run: |
          brew install cmake
      - name: Get code of gdal
        env:
          REPO_DIR: gdal
          WHEEL_SDIR: wheelhouse
          SETUPTOOLS_USE_DISTUTILS: stdlib
          BUILD_COMMIT: v3.4.3
        run: |
            bash -x .github/workflows/build.sh
      - name: Build Wheel of GDAL
        env:
          REPO_DIR: gdal/gdal/swig/python
          WHEEL_SDIR: wheelhouse
          SETUPTOOLS_USE_DISTUTILS: stdlib
          BUILD_COMMIT: v3.4.3
        run: |
            bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl
