---
name: MacOS wheels ARM64
on: [workflow_dispatch]
env:
  WHEEL_SDIR: wheelhouse
jobs:
  build_GDAL:
    name: GDAL ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["self-hosted"]
        python: ["3.12"]
        platform: ["arm64"]
        macos-target: ["12"]
        os-name: ["osx"]
    env:
      REPO_DIR: gdal
      BUILD_COMMIT: v3.7.3
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "numpy==1.26.2 wheel"
      TEST_DEPENDS: "numpy==1.26.2"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        run: |
          ls -lrt /opt/homebrew/bin/
          /opt/homebrew/bin/brew install cmake
          echo "check python3"
          python3 -c "import sys; print(sys.version)"
      - name: Get code of gdal
        env:
          REPO_DIR: gdal
          WHEEL_SDIR: wheelhouse
          BUILD_COMMIT: v3.7.3
        run: |
          bash -x .github/workflows/build.sh
      - name: Build Wheel of GDAL
        env:
          REPO_DIR: gdal
          WHEEL_SDIR: wheelhouse
          BUILD_COMMIT: v3.7.3
        run: |
          bash -x .github/workflows/wheel.sh
          sleep 3600
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse
