---
name: psutil wheels
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "tmate debugging enabled"
        required: false
        default: false
#  pull_request:
jobs:
  build_psutil:
    name: Build wheels of psutil  on "${{ matrix.os }}, ${{ matrix.arch }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, arch: x86_64 }
          - { os: ubuntu-24.04-arm, arch: aarch64 }
          - { os: macos-15, arch: x86_64 }
          - { os: macos-15, arch: arm64 }
          - { os: windows-2025, arch: AMD64 }
          - { os: windows-11-arm, arch: ARM64 }
    env:
      REPO_DIR: psutil
      BUILD_COMMIT: release-7.0.0
    steps:
      - uses: actions/checkout@v6
      - name: get code of psutil
        run: |
          echo $PATH
          bash -x .github/workflows/code.sh
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Build Wheel of psutil
        uses: pypa/cibuildwheel@v4.0.0
        env:
          CIBW_ARCHS: "${{ matrix.arch }}"
          CIBW_BUILD: "cp311-* cp312-* cp313-*"
          # This tells cibuildwheel to skip tests for all builds
          CIBW_TEST_SKIP: "*"
        with:
          package-dir: ./psutil
          output-dir: wheelhouse
