---
name: psutil wheels for x86_64 and arm64
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "tmate debugging enabled"
        required: false
        default: false
  pull_request:
env:
  WHEEL_SDIR: wheelhouse
jobs:
  build_psutil_OSX_arm64:
    name: psutils ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        python: ["3.11", "3.12", "3.13"]
        platform: ["arm64"]
    env:
      REPO_DIR: psutil
      BUILD_COMMIT: release-7.0.0
      WHEEL_SDIR: wheelhouse
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "wheel numpy==2.2.6 build pip==25.2 Cython==3.1.4 setuptools==80.9.0 tomli==2.2.1 versioneer[toml]==0.28"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
    steps:
      - uses: actions/checkout@v6
      - name: Get code of psutil
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          bash -x .github/workflows/build.sh
      - name: Build wheel of psutil
        run: |
          export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
          bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v7
        with:
          name: "wheels_psutil_${{ matrix.python }}_{{ matrix.platform }}"
          path: wheelhouse/psutil*whl

  build_psutil_Linux_x86_64:
    name: psutil ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python: ["3.11", "3.12", "3.13"]
        platform: ["x86_64"]
    env:
      REPO_DIR: psutil
      BUILD_COMMIT: release-7.0.0
      WHEEL_SDIR: wheelhouse
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "wheel numpy==2.2.6 build pip==25.2 Cython==3.1.4 setuptools==80.9.0 tomli==2.2.1 versioneer[toml]==0.28"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
    steps:
      - uses: actions/checkout@v6
      - name: Get code of psutil
        run: |
          bash -x .github/workflows/build.sh
      - name: Build wheel of psutil
        run: |
          bash -x .github/workflows/wheel.sh
      - uses: actions/upload-artifact@v7
        with:
          name: "wheels_psutil_${{ matrix.python }}_{{ matrix.platform }}"
          path: wheelhouse/psutil*whl
